### ISSUE TITLE
是凉了吗，每个节点都上不去

### ISSUE THREAD

**Issue by CassieZang** [shadowsocks/ShadowsocksX-NG#1187]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**Diagnoisis file:**

Please first upgrade to the latest version.
Then export the diagnosis file and upload it to here.

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by WienBC** [comment]
大佬，这邮件是github代发的吗？一下子收到无数封邮件。。


Japan-2的节点可以使用

 原始邮件
发件人: CassieZang<notifications@github.com>
收件人: shadowsocks/ShadowsocksX-NG<ShadowsocksX-NG@noreply.github.com>
抄送: Subscribed<subscribed@noreply.github.com>
发送时间: 2019年11月7日(周四) 16:56
主题: [shadowsocks/ShadowsocksX-NG] 是凉了吗，每个节点都上不去 (#1187)


Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

System and Shadowsocksx-NG version: (please complete the following information):

  *   OS Version: [e.g. 10.13.1]
  *   Version [e.g. 22]

Diagnoisis file:

Please first upgrade to the latest version.
Then export the diagnosis file and upload it to here.

ss-local.log

Please upload the ss-local.log file here the file is in ~/Library/Logs

  1.  Open 'Advanced Settings -> enable Verbose Mode'
  2.  Continue run Shadowsocksx-NG for 5 minutes
  3.  Upload the ~/Library/Logs/ss-local.log here (with or without compress)

Application log

Open the Console.app and search Shadowsocksx-NG
Copy paste the log here

Crash Log

If the app crashes and pop up a crash log, please copy and paste here

Additional context
Add any other context about the problem here.
