### ISSUE TITLE
Mac升级10.12.5后不能翻墙了

### ISSUE THREAD

**Issue by heartinfei** [shadowsocks/ShadowsocksX-NG#371]
今天升级Mac 到 10.12.5后发现所有的模式（pac，手动，全局）都不能翻墙了

**Comment by mk114** [comment]
进入ss-local目录  执行chmod +x ss-local  重启

**Comment by heartinfei** [comment]
@mk114 谢谢可以用了！😊

**Comment by nanacheung** [comment]
不会操作……/(ㄒoㄒ)/~~

**Comment by mk114** [comment]
@nanacheung 
打开终端，先执行
`cd /Applications/ShadowsocksX-NG.app/Contents/Resources`
然后
`chmod +x ss-local`
重启电脑
这是之前的操作，成功了。可是现在我却又用不了了。你先试试……

**Comment by qinyuhang** [comment]
raise a issue follow the issue template, then we will find out your problem easier. https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md

**Comment by nanacheung** [comment]
@mk114  谢谢你的指点~ 我试试看！

**Comment by kevinhee** [comment]
上面的方法都试过了，在windows下都正常，在mac上pac、全局、手动都不能用，还有什么权限或者监听端口没打开吗？

**Comment by mk114** [comment]
前往文件夹 

> ~/资源库/Application Support

删除其他的SS文件夹 只留一个  可能是ss-local 冲突

**Comment by cuteguy** [comment]
还是不好用。捉急呀

**Comment by richinyao** [comment]
version 10.12.5 (16F73) 各种模式都不能科学上网，期待早点能解决这个问题~

**Comment by qinyuhang** [comment]
上log。不给log怎么分析是哪里的问题？

**Comment by renweibo** [comment]
支持出问题后先给log

**Comment by Honliz** [comment]
可以发Shadowsocks Mac 客户端到我邮箱么，谢谢

**Comment by Honliz** [comment]
可以发Shadowsocks Mac 客户端到我邮箱么，谢谢 637035@qq.com

**Comment by renweibo** [comment]
@Honliz github上直接就可以下载，不需要别人发给你

**Comment by Honliz** [comment]
Dear :谢谢.当时尝试下载几次，每次到三分之一的时候就停止不动了，后来解决了。但是似乎还是不能用，不知道是二维码问题，还是软件不能用的问题，附上二维码，盼复，谢谢！------------------ 原始邮件 ------------------发件人: renweibo  <notifications@github.com>发送时间: 2017年9月30日 17:09收件人: shadowsocks/ShadowsocksX-NG <ShadowsocksX-NG@noreply.github.com>抄送: Honliz <justinsong0000@gmail.com>, Mention <mention@noreply.github.com>主题: 回复：[shadowsocks/ShadowsocksX-NG] Mac升级10.12.5后不能翻墙了 (#371)@Honliz github上直接就可以下载，不需要别人发给你

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shadowsocks/ShadowsocksX-NG","title":"shadowsocks/ShadowsocksX-NG","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/shadowsocks/ShadowsocksX-NG"}},"updates":{"snippets":[{"icon":"PERSON","message":"@renweibo in #371: @Honliz github上直接就可以下载，不需要别人发给你"}],"action":{"name":"View Issue","url":"https://github.com/shadowsocks/ShadowsocksX-NG/issues/371#issuecomment-333295567"}}}

**Comment by renweibo** [comment]
你还是来github直接下载吧，https://github.com/shadowsocks/ShadowsocksX-NG/releases
看不到你说的二维码，软件如果能下载安装的话，那比较可能是你的二维码的问题。

**Comment by evnydd0sf** [comment]
这两天 路由器配置的chacha20的加密被屏蔽 ss服务商又强制更新到了最新的加密 只能用shadowsocks 
然而之前Mac上的ss一直是不能用 今天下定决心准备弄好 在网上搜了两个多小时 最后查到是因为cleanmymac 在扩展的启动代理中 shadowsocks的代理被禁用了 只要打开 重启Mac就OK了

**Comment by hhx1994** [comment]
我的mac下载了ss的1.6.1版本，10月20日之前还能用的，现在不行了，mac系统是10.12.5的版本，求好心人解答是什么原因，祝好人一生平安。

**Comment by lrp1223** [comment]
同样各种不能用，求解答！

**Comment by LiuL0703** [comment]
解决了吗 MacOS 10.12.5

**Comment by yangfeicheung** [comment]
这个可以用
[Shadowsocks-X](https://github.com/yangfeicheung/Shadowsocks-X)

**Comment by lijianyu** [comment]
@evnydd0sf 代理都启用了，不过重启之后，其中一个代理又被禁止了

**Comment by yangfeicheung** [comment]
@Ipx84 哈哈，能用就好，有问题可以及时告诉我哈

**Comment by seaboyang** [comment]
本来用的R8一直很正常，别人给了个新加密的服务器就去下载了最新ss客户端，然后发现没有ssr又卸载了，这时侯R8客户端也用不了了。看到楼上说删除ss-local手滑把两个全删了。。。现在无法科学上网。急

**Comment by seaboyang** [comment]
R8卸载重装也没用。控制台一直报错2018-01-31 12:18:17 ERROR: remote_recv_cb_recv: Connection reset by peer

**Comment by rliuyi** [comment]
@yangfeicheung 现在 SS 还能用吗？我的好像不行。。。

**Comment by yangfeicheung** [comment]
@rliuyi 
Yes, you can try this one, if any problem, you can reach me via my email:
[Install SS on Mac](https://www.sednax.com/faq-0-cn.php)

**Comment by cloudyan** [comment]
亲测可用 https://github.com/shadowsocks/ShadowsocksX-NG/issues/939#issuecomment-435569249

**Comment by mcmicahelchan** [comment]
> @evnydd0sf 现场注册账号来给你点赞啊，SS终于能用了，居然是因为CLEAN MY MAC...泪流满面TAT...

想问一下在cleanmymac如何操作？是把这两个启用吗？🤔️
![image](https://user-images.githubusercontent.com/15685780/48929136-b20d2d00-ef20-11e8-9c13-c8865f1b61eb.png)

**Comment by ZhouChengHao** [comment]
> > @evnydd0sf 现场注册账号来给你点赞啊，SS终于能用了，居然是因为CLEAN MY MAC...泪流满面TAT...
> 
> 想问一下在cleanmymac如何操作？是把这两个启用吗？🤔️
> ![image](https://user-images.githubusercontent.com/15685780/48929136-b20d2d00-ef20-11e8-9c13-c8865f1b61eb.png)

是的，我是把所有启动项里包含SS的都开启就能用了

**Comment by MuTouzi** [comment]
![image](https://user-images.githubusercontent.com/58041254/133896108-05c30f94-83b8-4c29-b745-fd9995efb97f.png)
开上 能用了！！！！！
