### ISSUE TITLE
macOS 10.12.5(16F73) NG不起作用，有解决方式吗

### ISSUE THREAD

**Issue by Whi8per** [shadowsocks/ShadowsocksX-NG#381]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5 (16F73)
- Shadowsocksx-NG 1.5.1

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
  2017-05-25 20:46:28 INFO: initializing ciphers... aes-256-cfb
 2017-05-25 20:46:28 INFO: listening at 127.0.0.1:1080

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by garyzhalo** [comment]
别的评论里看到的，亲测可用：
https://github.com/shadowsocks/shadowsocks-iOS/releases

**Comment by richinyao** [comment]
System and Shadowsocksx-NG version:

    macOS 10.12.5 (16F73)
    Shadowsocksx-NG 1.5.1

Expected behavior:

Actual behavior:

(N/A for feature requests)

Steps to reproduce:

(N/A for feature requests)

How often does this happen?

(N/A for feature requests)

ss-local.log

Please upload the ss-local.log file here the file is in ~/Library/Logs

 2017-05-31 18:24:37 INFO: initializing ciphers... aes-256-cfb
 2017-05-31 18:24:37 INFO: listening at 127.0.0.1:1086

Application log

Open the Console.app and search Shadowsocksx-NG
Copy paste the log here

default	18:24:36.237746 +0800	ShadowsocksX-NG	Call SMLoginItemSetEnabled with [0] success
default	18:24:36.381160 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
default	18:24:36.448757 +0800	ShadowsocksX-NG	Stop privoxy succeeded.
default	18:24:36.513903 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
default	18:24:36.514802 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
default	18:24:36.573618 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [7389] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [7388] (3,0)
default	18:24:36.575477 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [7389] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [7388] (3,0)
default	18:24:36.578570 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [7389] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [7388] (3,0)
default	18:24:36.579613 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [7389] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [7388] (3,0)
default	18:24:36.584032 +0800	ShadowsocksX-NG	pac proxy set to global
default	18:24:37.550432 +0800	ShadowsocksX-NG	Start ss-local succeeded.


Crash Log

If the app crashes and pop up a crash log, please copy and paste here

**Comment by evanf** [comment]
@Whi8per
在~/Library/LaunchAgents/ 文件夹下是否有“com.qiuyuzhou.shadowsocksX-NG.local.plist”这样的文件？
貌似是系统升级后“LaunchAgents”文件夹的Owner变成root了，所以文件写不进去，Shadowsocks启动的时候找不到文件。
我在别人的电脑上试过把“LaunchAgents”这个文件夹写权限开放就能用了。

**Comment by colordove** [comment]
@evanf Hi,我看了下我的这个文件夹，“com.qiuyuzhou.shadowsocksX-NG.local.plist”这样的文件是存在的，权限也都设置成读写了，但好像还是无法使用。
