### ISSUE TITLE
Allow user to configure the proxy for Global/Automatic Mode to be HTTP Proxy

### ISSUE THREAD

**Issue by LukeXuan** [shadowsocks/ShadowsocksX-NG#393]
Currently, the global/automatic mode use SOCKS5 proxy as default. However, on MacOS many of the applications accepts HTTP proxy only(such as Google Drive). Currently I must choose manual mode and setup the system HTTP proxy.

I think adding this function would helps a lot.

**Comment by nriley** [comment]
This is definitely supported with the `proxy_conf_helper` tool built by ShadowsocksX.  I can find the [place in the code](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ShadowsocksX-NG/ProxyConfHelper.m#L135) where it is supposed to be called, too, but it is disabled because of #106.

Uncommenting the code in that method worked for me to reenable the HTTP proxy and I have not seen the privoxy error in #106.  So it should work for you too, and hopefully someone will be able to reproduce the privoxy error so the bug can be fixed!
