### ISSUE TITLE
PAC模式无法被Chrome的SwitchOmega扩展

### ISSUE THREAD

**Issue by dxvgef** [shadowsocks/ShadowsocksX-NG#497]
- macOS 10.12.6
- Shadowsocksx-NG 1.6.1
- Chrome 61.0.3163.91 (64 bit)
- SwitchOmega 2.5.2
<img width="665" alt="2017-09-18 22 33 39" src="https://user-images.githubusercontent.com/5192264/30547892-33f785dc-9c56-11e7-9391-f6d75b243ef6.png">
总是无法更新pac脚本

**Comment by holysky5** [comment]
经常不用啊

**Comment by timothyqiu** [comment]
Same versions here, and it works pretty fine.

Please provide the steps to reproduce the problem and the corresponding error messages / logs.

**Comment by dxvgef** [comment]
试了在SwitchyOmega里走SSX-NG的http、socket5代理模式都没问题，唯独用pac模式无法从http://127.0.0.1:1089/proxy.pac这个地址无法获取到pac脚本，我的SSX-NG用的是手动模式，这个地址是在用PAC自动模式时从网络设置里复制出来的，应该不会有错吧？但我直接在chrome里访问这个地址也无法连接。

**Comment by timothyqiu** [comment]
Manual Mode is for those who use the SOCKS5 proxy directly, so the PAC server is shutdown.

https://github.com/shadowsocks/ShadowsocksX-NG/blob/b31452e984f48d831fc8a913d8f8a6a2bf972911/ShadowsocksX-NG/AppDelegate.swift#L203-L213

Actually, since you're already using SwitchyOmega, using its builtin GFW List and whitelist features is a better choice.

**Comment by dxvgef** [comment]
手动模式没必要关闭pac代理吧？在windows上的shadowsocks就不会这样，SwitchyOmega的规则模式好像有内存溢出的情况，不敢用。

**Comment by timothyqiu** [comment]
Ever since Manual Mode was introduced in https://github.com/shadowsocks/ShadowsocksX-NG/commit/7590cf2b710ff8986ea5fbee9ce8715a74cc605d, the PAC server shuts down when Manual Mode is on. Whether we should change the behavior will be the decision of @qiuyuzhou.

FYI, shadowsocks-windows is fundamentally different from ShadowsocksX-NG. It handles different protocols on its own. That's also the reason why we don't have features like Load Balancing / High Availability among different servers here.

p.s. I have been using the Auto Switch mode of SwitchyOmega for years, and nothing bad ever happened.

**Comment by dxvgef** [comment]
@timothyqiu Ok! I used auto switch mode. Thank you!
