### ISSUE TITLE
关于Root权限的疑问

### ISSUE THREAD

**Issue by gonejack** [shadowsocks/ShadowsocksX-NG#649]
一直使用的是2016年的1.5.1版本，一切良好没什么问题。今天看到有更新试图更新，发现新版本的启动过长请求root权限，不理解要root做什么。

如果没有非常强烈需求的话，虽说是开源软件，但作为一个ss-local的图形界面需要请求root权限也不是什么好设计。

**Comment by timothyqiu** [comment]
SSX-NG is a thin GUI wrapper around several command line utilities. Global Mode and PAC Mode needs to modify your system network settings (making something like `ss-local` your current system network proxy), and that's why authorization is needed.

You can find out why authorization is needed by looking into the source code, and you can build it yourself if you don't trust the prebuilt binary. That's open source.

**Comment by gonejack** [comment]
开源也需要解释，开源的出发点应该是给大家提供一份安心省时的解决方案，简单而且人人都有的疑问都需要大家去翻源码的话，只能说作者缺少工作经验只会写代码。

```
networksetup -setwebproxy $NETWORK $HOST $PORT off
networksetup -setwebproxystate $NETWORK on

networksetup -setsecurewebproxy $NETWORK $HOST $PORT off
networksetup -setsecurewebproxystate $NETWORK on
```

据我所知上面这些命令是不需要ROOT权限的。

**Comment by timothyqiu** [comment]
It's two different things regarding "why" and "how to improve it".

* To find out _Why_ for some behavior, the __only__ source of truth is the source code. People can lie to you.
* If you have a better solution, Pull Requests are always welcome.

p.s. I'm not the author nor a maintainer, just a volunteer to help replying issues.

**Comment by gonejack** [comment]
Then I would say you help nothing at technical but making this issue a debate.
