### ISSUE TITLE
LSExceptions shared instance invalidated for timeout.

### ISSUE THREAD

**Issue by JadianZheng** [shadowsocks/ShadowsocksX-NG#712]
升级完最新的系统后，在系统日志中便显示如标题所示的语句，现在已经用不了，连不上代理

**Comment by JadianZheng** [comment]
@yangfeicheung 别骗人，明明就用不了

**Comment by yangfeicheung** [comment]
@JadianZheng  您要觉得是骗人的，那也没办法了，我这用的蛮好的

**Comment by vaful** [comment]
+1

**Comment by lining1991** [comment]
问题解决了么

**Comment by ShikiSuen** [comment]
@qiuyuzhou 我也遇到了这个问题，请重新开启该工单。
Shadowsocks 1.8.2, macOS Mojave 10.14.2.
(Windows 版 SS 一切正常，macOS 版是昨天東八區半夜開始罷工的、兩台電腦分別安裝的都罷工了。)

預設	17:50:59.650060 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.
預設	17:51:27.374074 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
預設	17:51:27.438555 +0800	ShadowsocksX-NG	Stop privoxy succeeded.
預設	17:51:27.439134 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
預設	17:51:27.543585 +0800	ShadowsocksX-NG	pac proxy set to off
預設	17:51:30.023273 +0800	ShadowsocksX-NG	Current system appearance, (HLTB: 2), (SLS: 1)
錯誤	17:51:30.026918 +0800	ShadowsocksX-NG	Unable to load Info.plist exceptions (eGPUOverrides)
預設	17:51:30.027607 +0800	ShadowsocksX-NG	Post-registration system appearance: (HLTB: 2)
預設	17:51:30.036296 +0800	ShadowsocksX-NG	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x60000384b480
 (
    "<NSDarkAquaAppearance: 0x600000e601c0>",
    "<NSSystemAppearance: 0x600000e60300>"
)>
錯誤	17:51:30.083752 +0800	ShadowsocksX-NG	        AEGetDescData of non-desc type 'reco' not a good idea
預設	17:51:30.128412 +0800	ShadowsocksX-NG	Call SMLoginItemSetEnabled with [1] success
預設	17:51:30.212252 +0800	ShadowsocksX-NG	Install ss-local succeeded.
預設	17:51:30.287673 +0800	ShadowsocksX-NG	generateSSLocalLauchAgentPlist - File has not been changed.
預設	17:51:30.288643 +0800	ShadowsocksX-NG	writeSSLocalConfFile - File has been changed.
預設	17:51:30.323716 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
預設	17:51:30.391599 +0800	ShadowsocksX-NG	Start privoxy succeeded.
預設	17:51:30.393269 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
預設	17:51:30.481397 +0800	ShadowsocksX-NG	pac proxy set to auto
預設	17:51:31.663745 +0800	ShadowsocksX-NG	Start ss-local succeeded.
預設	17:51:40.251804 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.
預設	17:54:14.189546 +0800	ShadowsocksX-NG	AggregateDictionary is not supported on this platform

**Comment by dixieboy** [comment]
我也出这个问题了。。。

> default	17:37:53.294067 +0800	ShadowsocksX-NG	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 224 vs 310, 640, <private>
default	17:37:58.503009 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.

**Comment by dixieboy** [comment]
> 我也出这个问题了。。。
> 
> > default	17:37:53.294067 +0800	ShadowsocksX-NG	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 224 vs 310, 640, 
> > default	17:37:58.503009 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.

哦。我这个是不能加载info.plist导致的。。

> default	17:41:26.209112 +0800	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : ShadowsocksX-NG
default	17:41:26.260975 +0800	launchservicesd	CHECKIN:0x0-0xb70b7 23765 com.qiuyuzhou.ShadowsocksX-NG
default	17:41:26.262970 +0800	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : ShadowsocksX-NG
default	17:41:26.294043 +0800	ShadowsocksX-NG	Current system appearance, (HLTB: 2), (SLS: 1)
default	17:41:26.299493 +0800	ShadowsocksX-NG	Post-registration system appearance: (HLTB: 2)
error	17:41:26.300532 +0800	ShadowsocksX-NG	Unable to load Info.plist exceptions (eGPUOverrides)
default	17:41:26.309848 +0800	ShadowsocksX-NG	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x6000034c0af0
 (
    "<NSDarkAquaAppearance: 0x6000002da100>",
    "<NSSystemAppearance: 0x6000002d9b00>"
)>
default	17:41:26.348124 +0800	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.qiuyuzhou.ShadowsocksX-NG, type: 0: 0x7ff8bd444c80 at /Applications/ShadowsocksX-NG.app
default	17:41:26.358165 +0800	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/ShadowsocksX-NG.app/Contents/Library/LoginItems/LaunchHelper.app/Contents/, NSFilePath=/Applications/ShadowsocksX-NG.app/Contents/Library/LoginItems/LaunchHelper.app/Contents/PlugIns, NSUnderlyingError=0x7ff05a793020 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	17:41:26.395955 +0800	ShadowsocksX-NG	Call SMLoginItemSetEnabled with [1] success
default	17:41:26.468461 +0800	ShadowsocksX-NG	Install ss-local succeeded.
default	17:41:26.564620 +0800	ShadowsocksX-NG	generateSSLocalLauchAgentPlist - File has not been changed.
default	17:41:26.566365 +0800	ShadowsocksX-NG	writeSSLocalConfFile - File has been changed.
default	17:41:26.598644 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
default	17:41:26.666776 +0800	ShadowsocksX-NG	Start privoxy succeeded.
default	17:41:26.669341 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
default	17:41:26.718544 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [23760] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [23790] (3,0) (engine 105)
default	17:41:26.731759 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [23760] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [23790] (3,0) (engine 106)
default	17:41:26.746760 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [23760] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [23790] (3,0) (engine 107)
default	17:41:26.761906 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [23760] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [23790] (3,0) (engine 108)
default	17:41:26.764258 +0800	ShadowsocksX-NG	pac proxy set to auto
default	17:41:27.758083 +0800	ShadowsocksX-NG	Start ss-local succeeded.
default	17:41:36.559067 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.

**Comment by liubinpoem** [comment]
我也出现了这个问题，求问如何解决

**Comment by stuartly** [comment]
请问如何解决的？

**Comment by BlackHole1** [comment]
+1

**Comment by Lanpice** [comment]
我也碰到这问题了...
Mac OS 10.13.6
昨天还能用，今天突然用不了了。

**Comment by sillykelvin** [comment]
我也出现过这个错误，服务器明明是好的，最后发现DNS有问题，在设置->网络->DNS里面改成四个8就可以了。

**Comment by PykeChen** [comment]
请问，解决了吗，我也遇到了这个问题，求助！！

**Comment by http600** [comment]
修改account name也会出现这个问题
