### ISSUE TITLE
Problems of user-rule.txt link

### ISSUE THREAD

**Issue by kator-278** [shadowsocks/ShadowsocksX-NG#72]
I moved my user-rule.txt to dropbox for keep-in sync and make a symbolic link instead, on `~/.ShadowsocksX-NG/user-rule.txt`.
But anytime when I edit my user-rule in ShadowsocksX-NG, the client it re-establishes a brand new user-rule.txt file instead of updating the real one which I've been moved on dropbox.
Of course I can use text editor instead, but I hope it would be fixed in future version.
Thanks.

**Comment by qinyuhang** [comment]
I think it is not a problem should be fix, because we never expect someone move user-rule.txt file and using a symbolic link replace it, the ShadowsocksX-NG will edit ` ~/.ShadowsocksX-NG/user-rule.txt` as a file, it will definitely work as you experience in your Mac.
Maybe you can try using shell script to copy ` ~/.ShadowsocksX-NG/user-rule.txt` to your dropbox folder?

**Comment by kator-278** [comment]
But is it weird that we have to sync files manually although dropbox or onedrive such of these can help us get rid of doing so? o.O
We don't want to sync up manually by copying user-rule.txt from one device to another (since a better solution is there), so could you tell me the reason why you must treat it as a file, and cover the symbolic link each time I edit it with the client?

**Comment by qinyuhang** [comment]
because it the logic that it idesigned…… the software store it there. Maybe
the will be a function allow choose customized config path.

kator-278 <notifications@github.com>于2016年9月28日 周三21:13写道：

**Comment by kator-278** [comment]
OK... Anyway it is not so serious the problem, I can use a text editor instead, it doesn't matter...
Thanks for your reply. :-)
