### ISSUE TITLE
"Proxy Auto Configure mode" does't work

### ISSUE THREAD

**Issue by SergeyChang** [shadowsocks/ShadowsocksX-NG#773]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 (16E????)
- Shadowsocksx-NG 1.7.1

**Expected behavior:**
work correctly

**Comment by timothyqiu** [comment]
Please help define "works" / "not working":
* What you did (step by step)
* What you expected to happen
* What actually happened

For example:
* I set SSX-NG to "Proxy Auto Configure mode" and opened Chrome 65.1.2.3 to baidu search "ip".
* The search result should show my local IP because `baidu.com` is whitelisted in my PAC.
* But the search result show my SS server IP, I think that's not working.

**Comment by shily** [comment]
Env:
- Mac os 10.13.4
- SS-NG 1.7.0 (1)

Steps:
- set up SS-NG to "Proxy Auto Configure mode"
- Update PAC from GFW lists
- set up chrome 66.0.3359.117 with Proxy Switcher 127.0.0.1:1086 socks-v5
- opened Chrome 65.1.2.3 to baidu search "ip"
except local ip 61.*.*.* but got 170.*.*.*

**Comment by timothyqiu** [comment]
@shily The "Proxy Auto Configure mode" only works through the system network setting (which is exactly your Proxy Switcher overrides).

You can set your Proxy Switcher to use either

1. The system proxy
2. The PAC url `http://127.0.0.1:1089/proxy.pac` (with 1089 being the default PAC port)
3. The AutoProxy rules file GFWList (`https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt`) if it's supported

p.s. I prefer SwitchyOmega to Proxy Switcher.
