### ISSUE TITLE
最新版的ShadowsocksX-NG集成了Privoxy吧，那么要如何在命令行下使用代理呢

### ISSUE THREAD

**Issue by cuidezhu** [shadowsocks/ShadowsocksX-NG#774]
**System and Shadowsocksx-NG version**

- macOS 10.13.3
- Shadowsocksx-NG 1.7.1

**Expected behavior:**
在命令行里使用代理，让命令通过代理进行执行

**Comment by xingjia10086** [comment]
如何下载最新的可以在mac用的软件？谢谢
发自网易邮箱大师
在2018年03月29日 01:52，Dezhu Cui 写道： System and Shadowsocksx-NG version

macOS 10.13.3
Shadowsocksx-NG 1.7.1

Expected behavior:
在命令行里使用代理，让命令通过代理进行执行

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shadowsocks/ShadowsocksX-NG","title":"shadowsocks/ShadowsocksX-NG","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/shadowsocks/ShadowsocksX-NG"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"最新版的ShadowsocksX-NG集成了Privoxy吧，那么要如何在命令行下使用代理呢 (#774)"}],"action":{"name":"View Issue","url":"https://github.com/shadowsocks/ShadowsocksX-NG/issues/774"}}}

**Comment by daveleenew** [comment]
。。。搞了一个晚上 。特么都链接不上。。晕死了。什么客户端啊。。

**Comment by SilgerZuo** [comment]
mac电脑不仅要正确使用客户端连接。
还要开启代理，点击右上角进入network preferrnce，选中自己的网路，在advance里有个proxy，配置proxy里面的socks proxy，可以直连远程，也可以连接127.0.0.1的本地端口.
下次不会用就乱喷客户端请不要用中文。真丢人。

**Comment by yangfeicheung** [comment]
To make is simpler, you can try our versions:

1. how to install
https://www.sednax.com/faq-0-cn.php

2. how to setup network:
https://www.sednax.com/help-network-cn.php
